version: '3'

# This docker-compose is for development only!
# You can also run a standard docker run command, see https://hub.docker.com/_/mysql
# This is easier to do just: docker-compose up -d

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    container_name: airflow_db
    env_file:
      - .env
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

